### ISSUE TITLE
should expression counts be normalized in the 2d expression matrix?

### ISSUE THREAD

**Issue by frankysuperior** [gangwug/MetaCycle#12]
Hi, thanks for providing this wonderful tool, but I am wandering (1) can this be applied to RNA-seq data? (2) should the expression counts  be normalized in the 2d expression matrix? for example, in the form of raw counts, or log transformed data, or RPKM, etc.? (3) can this tool be applied to large scale data sets such as single cell RNAseq, say, 2000 cells for each time point, and 6 time points in total? greatly appreciate your reply!

**Comment by gangwug** [comment]
Hi, thanks for interesting with MetaCycle. For your questions:
*"(1) can this be applied to RNA-seq data?"*
Yes.

*"(2) should the expression counts be normalized in the 2d expression
matrix? for example, in the form of raw counts, or log transformed data, or
RPKM, etc.?"*
Yes, normalization is suggested. There is a limited comparison study on raw
counts, log-transformed data, RPKM, and TPM. TPM from Kallisto or RSEM
seems good.

*"(3) can this tool be applied to large scale data sets such as single cell
RNAseq, say, 2000 cells for each time point, and 6 time points in total?"*
Yes. Possibly need to average multiple cells in each cell type and run it
cell type by cell type.

Best wishes!

Gang
