### ISSUE TITLE
JTK & non-integer interval

### ISSUE THREAD

**Issue by maque4004** [gangwug/MetaCycle#15]
Hi, Dr. Gang Wu,
Thank you for sharing such powful tool. My data is 0.5-hour-resolution with missing values, I ran JTK_cycle on my data. 
![image](https://user-images.githubusercontent.com/45165322/86532774-fb946b00-befe-11ea-9a61-679f60fd7d5b.png)
from the docs, JTK is not suitable for non-integer interval.
There is one line in the Rscript to set interval length: jtk.init(period, interval), I set the interval to be 1, and also 0.5, other parameters in the script are same,  it turned out that I got the same rhythmic genes.
My question is: if the interval is non-integer, maybe I can treat it as an interval(like one hour), the interval length should not rhythmic pattern? 

Thank you very much for your help in advance!

Best,
Yichen Hu

**Comment by gangwug** [comment]
Hi Yichen,

I would suggest transforming 0.5h to 30 minutes, and re-run MetaCycle with
period length as 1440 for searching circadian signals.

Best wishes!

Gang
