### ISSUE TITLE
Error: invalid argument to unary operator

### ISSUE THREAD

**Issue by maque4004** [gangwug/MetaCycle#16]
Hi Dr. Wu,

while I was running meta_2d function, an error raised: Error in -JTK.ALT[[alt.id]]$EXV : invalid argument to unary operator
my data contains missing values, sample intervals are 30 min, intested period is 1080 min, so my codes are
`meta2d(infile = 'foo.csv', outdir = 'foo', filestyle = 'csv', timepoints = 'line1', minper = 1020, maxper = 1140, cycMethod = c("ARS", "JTK", "LS"), analysisStrategy = "auto", ARSdefaultPer = 1080)`

I know my data is not suitable for ARS method, I just set the default parameters.
Details:
![image](https://user-images.githubusercontent.com/45165322/88055514-b7a59500-cb91-11ea-9f7e-118eb69a9c25.png)

R version 4.0.0 
MetaCycle_1.2.0
[foo.txt](https://github.com/gangwug/MetaCycle/files/4953519/foo.txt)
I hava also attached input file here. It was comma seperated, could you please kindly help me to check what was going wrong, thank you very much!

Best,
Hu Yichen

**Comment by gangwug** [comment]
Hi Yichen,

Will check this error from JTK. In my experience, LS is better than JTK for
profiles with so many time points. So I would suggest only applying LS for
your data.

Best wishes!

Gang

**Comment by maque4004** [comment]
Hi Dr. Wu,

Thanks for suggestion~ I've compared JTK and LS method using a test dataframe, it seemed JTK get more rhythmic genes than LS,  I plotted the gene expressions along time,  from the plot, JTK results seemed acceptable.

I used JTK Rscripts, also got the same error`Error in -JTK.ALT[[alt.id]]$EXV : invalid argument to unary operator`. Do you have any idea why this error was raised? 

Another question:
while running meta2d function, lots of warming: `NA/Inf replaced by maximum positive value ` were raised when using the LS method, did it influence the reliability of the results?

Sorrry, I can not understand how these methods work in detail, so I have lots of stupid questions, thank you again for your kindly help!

Best,
Yichen

**Comment by gangwug** [comment]
Hi Yichen,

No problem. All are good questions. A kind of busy these days, can not
response your email in time. For the LS question, I do not think that
warnings will influence the reliability of the results. For the JTK
question, let me write an email to Matt and see whether he met similar
issues during preparing his package.

Best wishes!

Gang

**Comment by gangwug** [comment]
Hi Matt,

Did you ever meet the similar error as Yichen when you run JTK through your
DiscoRhythm package?

Best wishes!

Gang

**Comment by gangwug** [comment]
Hi Yichen,

The issue may be associated with the number of input time points. Your data
has 189 time points. The JTK does not handle data with more than 170 time
points. Not a usual issue.

Best wishes!

Gang

**Comment by maque4004** [comment]
Dear Dr. Wu,

Thanks a lot for debugging and clear explanation!

Best,
Yichen
