### ISSUE TITLE
question regarding adj P value and JTK_BH.Q

### ISSUE THREAD

**Issue by yxiao832** [gangwug/MetaCycle#17]
Hi Dr. Wu, 

I used metacycle to analyze a RNA-seq dataset, which has 4 integer time points and 3 replicates in each time point.

The command line I used is 
>meta2d(infile="allmerged_colnames.csv", filestyle = "csv",outdir="JTK",timepoints="Line1",cycMethod="JTK")

The metacycle output generates two P value for each transcript - adj P and BH-Q. To my understanding, adj P was calculated by Bonferroni test and BH-q was calculated by Benjamini-Hochberg. 

I am wondering which P value would you recommend to use? I am asking because my BH-Q test only give either 1 or 0.59 for all transcripts, which means probably none of these genes are cycling, but adj P can give me about 1000 cycling transcript if I set the cutoff to < 0.05.

Thank you!

Yang

**Comment by gangwug** [comment]
Hi Yang,

If selecting both JTK and LS, will the sparse BH.Q values be improved? When
the sampling resolution is pretty low, it is usually not good to do the
rhythmic test. ANOVA could be used to test the influence of time.

Best wishes!

Gang

**Comment by yxiao832** [comment]
Thank you very much! I will try it!
