### ISSUE TITLE
meta2d

### ISSUE THREAD

**Issue by yuan596** [gangwug/MetaCycle#19]
hello，
![image](https://user-images.githubusercontent.com/55010832/192182534-92c5c33d-5221-4447-91d3-688c9e697d1e.png)

![image](https://user-images.githubusercontent.com/55010832/192182517-abd148e3-8e63-436f-b478-305b5791c71a.png)
I don't known why

**Comment by gangwug** [comment]
Please have a try the below codes:

library(MetaCycle)
write.csv(cycSimu4h2d, file="example.csv", row.names=FALSE)testD <-
read.csv("example.csv")timev <- seq(0,44,by=4)outD <-
meta2d(infile="csv", filestyle="csv", timepoints = timev,
outputFile=FALSE, inDF=testD)

Best wishes!

Gang

**Comment by yuan596** [comment]
thank you ！
