### ISSUE TITLE
input data file format?

### ISSUE THREAD

**Issue by stevendbrown** [gangwug/MetaCycle#2]
The input format description is severely lacking. Can you post some sample input files (e.g. sample CSV files) and the corresponsing `filestyle` parameters used to load them?

**Comment by gangwug** [comment]
There are several example datasets wrapped into the package. Please take a
look at page 9 of the attached introduction file.


Best wishes!

Gang Wu

**Comment by stevendbrown** [comment]
Hi,

Can you link to the CSV or TXT file included with the package? There do not seem to be any CSV or TXT files in the repository.

Thanks,
Steve

**Comment by gangwug** [comment]
Hi Steve,

The data is rda type in R, which needs to write them out as txt or csv
file. For the csv or txt example, you could found some here:
https://github.com/gangwug/SRBR_SMTSAworkshop/tree/master/data.



Best wishes!

Gang Wu

**Comment by stevendbrown** [comment]
Hi Gang,

Thanks for that link, it is very helpful. Do I understand correctly that when specifying `timepoints='Line1` in the `meta2d` command, the contents of the header line in the first column don't matter?

Thanks again,
Steve

**Comment by gangwug** [comment]
Hi Steve,

No problem. Yes, you are right.

Best wishes!

Gang Wu
