### ISSUE TITLE
Error in Meta2D: Subscript out of Bounds

### ISSUE THREAD

**Issue by annfe** [gangwug/MetaCycle#20]
Hello,

I have been running meta2d with the following command:

meta2d(infile="my file.csv", timepoints="line1", filestyle="csv", maxper=26, cycMethod=c("JTK","LS"))

I have used this command on 6 different files that are all formatted identically with an identical gene list. The timepoints are in the top row, and the gene names are in the first column.

When I run this command on these files, 5 of 6 files run perfectly.  On the 6th file, I get the following error:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/118568504/202802620-695fe158-6cea-4b32-9f6c-429cf3b48cd9.png">

Any ideas what might be causing this error and how I could go about fixing it?

Thanks for any advice you might have!

**Comment by gangwug** [comment]
Hi,

Did you check whether there are some rows in file 6 contain constant values?

Best-
Gang

From: annfe ***@***.***>
Date: Friday, November 18, 2022 at 4:08 PM
To: gangwug/MetaCycle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gangwug/MetaCycle] Error in Meta2D: Subscript out of Bounds (Issue #20)

Hello,

I have been running meta2d with the following command:

meta2d(infile="my file.csv", timepoints="line1", filestyle="csv", maxper=26, cycMethod=c("JTK","LS"))

I have used this command on 6 different files that are all formatted identically with an identical gene list. The timepoints are in the top row, and the gene names are in the first column.

When I run this command on these files, 5 of 6 files run perfectly. On the 6th file, I get the following error:

[image]<https://user-images.githubusercontent.com/118568504/202802620-695fe158-6cea-4b32-9f6c-429cf3b48cd9.png>

Any ideas what might be causing this error and how I could go about fixing it?

Thanks for any advice you might have!

**Comment by annfe** [comment]
Hi Gang,

I did have some constant values in file 6.  I also had constant values in file 5 (which ran just fine).  Additionally, removing the constant values from file 6 did not cause the error to stop occurring.  I continue to get the same error that I had reported in my previous post.

**Comment by annfe** [comment]
Hi Gang,

With quite a bit of playing around with my dataset I was able to determine that the error that I first presented and the warnings were caused by different genes.  I determined this by subsetting my rows of data into smaller chunks until I found the line that was responsible for causing the error.  As a note, I only did these subsets on the genes that didn't have constant values - I had removed all the constant value genes prior to starting my subsetting.

The error which caused the program to break was:


individual gene that caused the error had the following expression pattern:

<STUFF>


Also, while I was doing this, I encountered the following warning messages, all on different subsetted runs that had otherwise finished:

Error message #1
<img width="650" alt="image" src="https://user-images.githubusercontent.com/118568504/204563809-017222e6-d591-4908-ab3c-2eb3b77fe539.png">

Error message #2
<img width="500" alt="image" src="https://user-images.githubusercontent.com/118568504/204566104-617c3a89-5e60-408d-81a0-d6f5a0bb2a39.png">

Would you be able to provide any information about how this may affect my results?

Thanks again!

**Comment by annfe** [comment]
Hi Gang,

With quite a bit of playing around with my dataset I was able to determine that the error that I first presented and the warnings were caused by different rows.  

The error which caused the program to not finish was:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/118568504/204567230-4f314c08-8644-42ec-ba1f-cfa0d4bb460e.png">

I discovered was that somehow all but one value in one of the rows was NA.  When I removed that row, I still got a couple of warnings (see below), but I no longer got the error and the program was able to run to completion.

Warning #1
<img width="650" alt="image" src="https://user-images.githubusercontent.com/118568504/204563809-017222e6-d591-4908-ab3c-2eb3b77fe539.png">

Warning #2
<img width="500" alt="image" src="https://user-images.githubusercontent.com/118568504/204566104-617c3a89-5e60-408d-81a0-d6f5a0bb2a39.png">

I can get rid of warning #2 by removing the row that had the 2nd fewest datapoints that were not NA (3 values, one at one timepoints and two at another timepoints), but warning #1 persists.  I can also state that warning #1 comes from the LS portion of the command, as if I only ask it to perform JTK (on the file where the 2 rows with only 1 or 3 non-NA values have been removed) the error does not occur. Removing the row with the next highest number of NA values (11 non-NA values spread across 8 of my 13 total timepoints) didn't cause warning #1 to go away.

I am more interested in JTK than LS, so I am content at this point with this resolution, but if you have any suggestions that you would like me to take a look at to investigate further I would be happy to do so.

**Comment by gangwug** [comment]
Hi, it is a good test. MetaCycle should handle the NA issue. Would you like
to try the GitHub version (https://github.com/gangwug/MetaCycle)? For those
rows with many missing values, I suggest removing them before running JTK.

Best wishes!

Gang

**Comment by gangwug** [comment]
Close
