### ISSUE TITLE
MetaCycle  meta2d

### ISSUE THREAD

**Issue by yuan596** [gangwug/MetaCycle#21]
why does the result of meta2d function show nan value?

JTK_period	JTK_adjphase	JTK_amplitude	meta2d_Base	meta2d_AMP	meta2d_rAMP
0	NA	0	0	NA	NA

**Comment by gangwug** [comment]
Out of the detection range of JTK.

**Comment by yuan596** [comment]
what is the detection range of JTK?








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gangwug/MetaCycle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 凌晨0:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gangwug/MetaCycle] MetaCycle  meta2d (Issue #21)





 
Out of the detection range of JTK.

**Comment by gangwug** [comment]
https://cran.r-project.org/web/packages/MetaCycle/vignettes/implementation.html

**Comment by gangwug** [comment]
Done
