### ISSUE TITLE
problem of using ARS.R

### ISSUE THREAD

**Issue by hygine** [gangwug/MetaCycle#3]
my code like this:
`runARS(fpkm,ARStime = 24,minper = 20,maxper = 28,arsper = 24,arsmet = "mle",releaseNote = T)
`
my data of fpkm like this:
`head(fpkm )`
              GeneID          2           6          10          14          18          22
1 ENSMUSG00000000001 39.2423000 53.30970000 45.74855000 48.16060000 50.86520000 43.88400000
2 ENSMUSG00000000028  0.7999640  1.04892201  1.03209000  0.88276200  0.75456200  0.60465828
3 ENSMUSG00000000037  0.0647347  0.04107064  0.07675234  0.02379874  0.04734312  0.06447354
4 ENSMUSG00000000049  5.3027700  9.22718000  7.01244000  5.88129000  6.76613000  7.76443900
5 ENSMUSG00000000056  9.3720300 11.69575600 10.73397000  9.05826000  9.78742000  7.47848200
6 ENSMUSG00000000058 21.7220940 21.10826826 23.26603702 25.86059600 26.37826686 23.11869876

with error message like this:
```
 Error in if (set_order == length(self.x)) { : 
  missing value where TRUE/FALSE needed 
3.
get_period(per.x = eva.x, per.dt_y = eva.dt_y, per.delta = eva.delta, 
    per.pID = eva.pID, is_filter = p1, ar_method = p2) 
2.
evaluate(eva.x = time_points, eva.y = dataM[line, ], eva.delta = self.delta, 
    eva.pID = line, T_start = start, T_end = end, T_default = arsper, 
    arsmethods = arsmet) 
1.
runARS(fpkm, ARStime = 24, minper = 20, maxper = 28, arsper = 24, 
    arsmet = "mle", releaseNote = T) 
```

best wish.

**Comment by gangwug** [comment]
It seems that one key parameter-'ARStime' was not set.

**Comment by gangwug** [comment]
If setting 'ARStime = c(2, 6, 10, 14, 18, 22)', it may not report this error. In addition, I would suggest to try meta2d to run 'ARSER', which has good example to follow.

**Comment by hygine** [comment]
thanks, finally I run meta2d to fixed my problem.
