### ISSUE TITLE
Input data.frame instead of text

### ISSUE THREAD

**Issue by thiagomaf** [gangwug/MetaCycle#7]
Dear all,

First of all, many thanks to the author. Great work.

I have been wondering if there is any known reason why not to implement the meta2d (or even the meta3d) functions to receive data.frame (even better if melted).

I have been playing with the code and I can already input data.frames in the format especified for the text files. Would it be interesting for the community to have the meta2d altered to receive melted tables?

Best wishes,
Thiago

**Comment by gangwug** [comment]
Hi Thiago,

Thanks for the advice. When we design meta2d, one aim is to analyze
multiple time-series datasets in a easier way. We thought it would be
easier if accepting input files. Considering the code structure, an easier
way of accepting melted data frame may be spreading the melted data back to
the time-series data frame.

Best wishes!

Gang
